### ISSUE TITLE
rgdal and rgeos will retire

### ISSUE THREAD

**Issue by edzer** [nplatonov/ursa#1]
Dear maintainer,

as you may have noticed from the `rgdal` startup messages, or [this blog post](https://r-spatial.org/r/2022/04/12/evolution.html), or from my 2021 UseR! keynote, rgdal, rgeos and maptools will soon retire. We found out from reverse dependency checks, and looking at concrete dependencies summarized in [this table](https://r-spatial.github.io/evolution/report.html#by-depending-package) that this package heavily depends on these retiring packages, and in particular on low-level functions like `GDAL.open` that will not have obvious successors in more modern packages. Please confirm that you are aware of this, and let us know if you have particular questions.

Cc: @rsbivand

**Comment by nplatonov** [comment]
Confirm this.

**Comment by rsbivand** [comment]
You will note that **rgdal** 1.6-2 released a month ago deprecated a number of functions and methods. **ursa** uses at least:
```
rgdal::closeDataset rgdal::CRSargs rgdal::GDAL.close rgdal::GDALcall rgdal::GDALinfo rgdal::getDriver rgdal::getDriverName rgdal::getRasterData rgdal::ogrInfo rgdal::ogrListLayers rgdal::project rgdal::putRasterData rgdal::readOGR rgdal::saveDataset rgdal::setCPLConfigOption rgdal::showP4 rgdal::showWKT rgdal::writeOGR rgeos::gBuffer rgeos::gDifference rgeos::gIntersection rgeos::gIsValid rgeos::gLength rgeos::gSimplify rgeos::gSymdifference rgeos::gUnaryUnion rgeos::gUnion rgeos::readWKT
```
in code. We expect to retire **rgdal** during 2023. No package uses **ursa**, so we do not need to take extra measures to encourage you to upgrade your package or to drop it and rather use other packages directly in your workflows. We will not contact you again.

**Comment by rsbivand** [comment]
Now also a deprecation in submitted **rgeos**:
```
Package: ursa
Check: Rd cross-references
New result: WARNING
  Missing link or links in documentation object ‘spatial_engine.Rd’:
    ‘[rgeos:misc-gBuffer]{gBuffer}’
  
  See section ‘Cross-references’ in the ‘Writing R Extensions’ manual.
```
Link to `rgeos-deprecated` if really needed.

This is as of 2022-12-19 giving CRAN warnings.

**Comment by rsbivand** [comment]
New blog: https://r-spatial.org/r/2022/12/14/evolution2.html

Best complete by June 2023 latest.

**Comment by rsbivand** [comment]
Since **terra** and **sf** do not expose low-level access to GDAL in R code, perhaps look at https://github.com/hypertidy/vapour, and work with its developer to add in anything you still need. You should take action urgently, we expect to make breaking changes in June 2023.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

Action now is essential.

**Comment by rsbivand** [comment]
@nplatonov Note that https://cran.r-project.org/package=gdalraster is on CRAN providing low-level access to GDAL. See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN; you were first warned more than nine months ago.

**Comment by rsbivand** [comment]
@nplatonov Your new version does not remove `rgdal` as an import or `rgeos` as suggested. You need to replace `rgdal` for example as I suggested earlier by `gdalraster` within 5 weeks, as the retiring packages will be gone early in October.

**Comment by rsbivand** [comment]
@nplatonov Less than three weeks remain to fix this.
